### PR TITLE
Upgrade cloudscraper and other dependencies

### PR DESCRIPTION
**Pull request by grrttedwards**
Potential fix for what's being seen by some people over in #99 

Upgrades dependencies. Running a `pipenv install` will bring in the new dependencies.

This is working for me on Curse out of the box with my testing profile.

### CODE REVIEW

**Comment by olepg** [comment]
I've downloaded the new files, ran `pipenv install` and `pipenv clean`, but I still get the same error:
Failed to find addon version number for game version: GameVersion.classic, https://www.curseforge.com/wow/addons/exorsus-raid-tools

**Comment by grrttedwards** [comment]
:( @olepg 

I can pull and update that addon.

```
(wow-addon-updater) > pipenv run python -m updater -c config-test.ini
Installing/updating addon: exorsus-raid-tools to version: Exorsus Raid Tools v.4110 Classic...


Name                               Prev. Version                      New Version
────                               ─────────────                      ───────────
QuestIconDesaturation              3.1                                Up to date
elvui|ElvUI                        v11.312                            Up to date
deadly-boss-mods|DBM-Azeroth       1.13.30-classic                    Up to date
FiveSecondRule                     069b51e                            Up to date
ctmod|CT_BarMod                    8.3.0.2 Classic                    Up to date
TinyDPS|Fonts                      50a4a34                            Up to date
exorsus-raid-tools                 -----                              Exorsus Raid Tools v.4110 Classic

```

When you say "downloaded the new files", do you mean you took the changes here, or you downloaded the `master` branch?

Can you show me the output of you running `pipenv graph` ?

**Comment by olepg** [comment]
I downloaded the files under "Branch: upgrade-dependencies".

`>pipenv graph
-rotli==1.0.7
beautifulsoup4==4.8.2
  - soupsieve [required: >=1.2, installed: 1.9.5]
cloudscraper==1.2.20
  - requests [required: >=2.9.2, installed: 2.22.0]
    - certifi [required: >=2017.4.17, installed: 2019.11.28]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.7]
  - requests-toolbelt [required: >=0.9.1, installed: 0.9.1]
    - requests [required: >=2.0.1,<3.0.0, installed: 2.22.0]
      - certifi [required: >=2017.4.17, installed: 2019.11.28]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.7]`

**Comment by grrttedwards** [comment]
Unfortunately that looks fine. It's really bothering me I can't reproduce these issues many people are having!

**Comment by jaredm4** [comment]
It works! I got a new openssl error on python 3.7.2 on Windows saying openssl was too old to work with cloudflare's 1.3 TLS, but an upgrade to python worked.

Upgraded to Python 3.8, then set pipenv to use it ```pipenv --python 3.8.1```, ran ```pipenv install``` and it worked!

Thanks! See you again soon when Curse decides to be a tool again.

**Comment by olepg** [comment]
Confirmed, `pipenv --python 3.8.1` did the trick

**Comment by grrttedwards** [comment]
Hmm.... I'm actually running 3.7.4 and don't see those issues. But it's great that this is working again for the both of you!

**Pull request merged**
