### PR TITLE
Update TukUI Download Code

### LINKED ISSUE #111: TukUI Addons Fail to Download
I'm having a bit of trouble with getting the program to download any addon from TukUI that's not ElvUI. For example, listing [https://git.tukui.org/Azilroka/AddOnSkins/](https://git.tukui.org/Azilroka/AddOnSkins/) in addons.txt and running the program, the add-on isn't listed as one to check for updates or install.

I've pinned it down to what I believe being the problem, the tukui.py site URL seems to have hard-listed as ElvUI's git page.

` class Tukui(AbstractSite):`
`    _URLS = [`
`        'https://git.tukui.org/elvui/'`
`    ]`

Removing `elvui/` from the URL gets it to download properly. There may be a reason it's hard-coded, so I thought I'd raise a ticket rather than a pull request.

Some addons are also not listed in their git repo, but are listed on the main website, so it makes it difficult to get them updated. Some repos also house both the classic and retail versions of add-ons in one, so it makes it difficult to separate them (there's also no common folder structure).

I did notice that an add-on through their main website, [https://www.tukui.org/classic-addons.php?id=2](https://www.tukui.org/classic-addons.php?id=2), has an extras tab which contains version information:

image

I can look into the possibility of using this as version information, allowing more add-ons to be installed and updated.

### PR DESCRIPTION
**Pull request by Audited**
Updated the structure for TukUI to match that of their main website. This refactor now allows for the download and installation of any addon (both classic and retail) by using the TukUI main website, rather than the repo (not all projects seem to be publically listed on there).

Updated the test cases and removed specialised coding for the unzipping of the addon, as the main website does not have subfolders any more.

Updated documentation to include sample TukUI links and to remove mention of subfolder formatting for TukUI.

Tested with ElvUI, ElvUI Nuts and Bolts and AddOnSkins. Test cases also came back positive.

I'm not much of a programmer, so there may be some inefficiencies in my code.

Fixes #111

### CODE REVIEW

**Comment by Audited** [comment]
Let me know if I need to update anything to match master.

**Comment by grrttedwards** [comment]
Hi! @Audited I'm finally reviewing this, between computer issues and being stuck inside definitely not helping my motivation.

I don't actually use TukUI or ElvUI, but the code looks fine to me, and I'll trust it's working for you. Just one question: if someone was using what will become the old git-repo style links, does this break for them? What would they have to do to migrate?

**Comment by grrttedwards** [comment]
Not sure why Travis is reporting the tests passing -- they are definitely not passing due to the Curse / Cloudflare issues

**Comment by Audited** [comment]
> I don't actually use TukUI or ElvUI, but the code looks fine to me, and I'll trust it's working for you. Just one question: if someone was using what will become the old git-repo style links, does this break for them? What would they have to do to migrate?

Good point on this part. With this update, the old URL is completely ignored, and is no longer updated. The old URL only allowed for ElvUI to be downloaded anyway, so I believe in this case that the effects will be minimal.

We can add some info to the README, but I'm worried it's getting a little bit too large now. Would it be possible to look at creating a Wiki for this project? A note for the next release concerning this could be beneficial too.

While I'm not much of a coder, I love writing documentation (I don't know why), so I'm happy to help with that if needed.

**Comment by Audited** [comment]
I didn't mean to close this pull.... I swear I'm good with Github!

**Comment by grrttedwards** [comment]
Will release this hopefully soon, kind of want to wait for Curse to be working again 🙄

**Pull request merged**
